# WAF Platform - Docker Compose Production Override

# This file extends the base docker-compose.yml for production deployment
# Usage: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d

version: '3.8'

services:
  backend:
    environment:
      - LOG_LEVEL=WARNING
      - DATABASE_URL=postgresql://waf_user:${DB_PASSWORD}@db:5432/waf_db
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

  frontend:
    environment:
      - NODE_ENV=production
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.25'

  nginx:
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.1'

  db:
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

  redis:
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.1'
